apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "exporter.names.fullname" . }}
  labels:
  {{- include "common.labels" . | nindent 4 }}
  {{- include "server.labels" . | nindent 4 }}
data:
